### ISSUE TITLE
Bungeecord plugin: Specifying address/port in remote config doesn't work

### ISSUE THREAD

**Issue by WOo0W** [GeyserMC/Geyser#1110]
**Describe the bug**

Changing the config of `remote` selection in `plugins/Geyser-BungeeCord/config.yml` doesn't take effect. The plugin gets the host info only from the Waterfall config.

We are using Waterfall behind a haproxy server with Waterfall's `proxy_protocol` enabled. Directly connect to the server with Waterfall's listening host using Minecraft JE causes `Timed out` error. We tried to change the remote host to haproxy server but changing the remote address and port in Geyser's config file doesn't work.

We tried to use standalone version to connect to the haproxy address and everything works well. With Bungeecord plugin version it always says `Read time out` in console(It connects to Waterfall directly).
```
[23:15:25 INFO] [Geyser-BungeeCord]: User has disconnected from remote Java server on address 172.x.x.x because of Read timed out.
[23:15:25 ERROR]: org.geysermc.platform.bungeecord.shaded.netty.handler.timeout.ReadTimeoutException
[23:15:25 INFO] [Geyser-BungeeCord]: Bedrock user with ip: /x.x.x.x has disconnected for reason CLOSED_BY_REMOTE_PEER
```
The haproxy is listening on `0.0.0.0:25565`, the Waterfall itself is listening on a private address `172.x.x.x:25577`.

```
remote:
  # The IP address of the remote (Java Edition) server
  address: 127.0.0.1
  # The port of the remote (Java Edition) server
  port: 25565
  # Authentication type. Can be offline, online, or floodgate (see https://github.com/GeyserMC/Geyser/wiki/Floodgate).
  auth-type: online
```
After changing the config to this, Geyser still uses 172.x.x.x:25577 as host.

**To Reproduce**

Change the `address` and `port` in `remote` selection in `config.yml`

**Expected behavior**

The host config of Geyser should follow the `config.yml`.

**Server Version**

`This server is running Waterfall version git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8afc4e2:366 by md_5`

**Geyser Version**

`(git-master-3ef7e30) (Java: 1.16.1, Bedrock: 1.16.0)`

**Minecraft: Bedrock Edition Version**

1.16.0

**Comment by rtm516** [comment]
This was an intended change but by the sounds of it we should add some form of override for cases like this.

**Comment by DoctorMacc** [comment]
Could you please provide a Geyser dump of Geyser on the BungeeCord instance?

**Comment by WOo0W** [comment]
> Could you please provide a Geyser dump of Geyser on the BungeeCord instance?

https://dump.geysermc.org/babY1prWwLRa8SCsWojSOFvxAtSkjdm2

**Comment by DoctorMacc** [comment]
Does setting the remote address to `43.248.186.16` fix it?

**Comment by WOo0W** [comment]
> Does setting the remote address to `43.248.186.16` fix it?

We have tried to set the remote address to `127.0.0.1:25565` and `43.248.186.16:25565`, Geyser still uses `172.28.84.37:25577` as its remote address.

```
[09:42:19 INFO] [Geyser-BungeeCord]: User(logged in as: User) has connected to remote java server on address 172.28.84.37
...
[09:42:49 INFO] [Geyser-BungeeCord]: User has disconnected from remote Java server on address 172.28.84.37 because of Read timed out.
[09:42:49 ERROR]: org.geysermc.platform.bungeecord.shaded.netty.handler.timeout.ReadTimeoutException
```

**Comment by DoctorMacc** [comment]
https://github.com/GeyserMC/Geyser/pull/998 does this PR allow you to connect? You can click on Checks and then click on Artifacts to get a build.

**Comment by WOo0W** [comment]
With this PR the remote config seems are still ignored by the plugin versions of Geyser.
https://github.com/GeyserMC/Geyser/pull/998/files#diff-2aafc9b81caac90eaa4ef17397c1abb4R20
`# The following two values are ignored for plugin versions`

Our Bungeecord is listening on `172.28.84.37:25577`. However, with `proxy_protocol` enabled on Bungeecord, directly connecting to this address will not work. We need Geyser to connect to another address like `127.0.0.1:25565` or `43.248.186.16:25565`(A haproxy server). But the remote config is ignored for the plugin versions.

We can add a config to make the plugin versions use the remote host defined in `config.yml` instead of getting the Bungeecord's listening address or just localhost.
```yaml
remote:
  # With follow-config enabled plugin versions still use the following two values
  # instead of the listening address of Bungeecord or Minecraft server.
  follow-config: false
  # The IP address of the remote (Java Edition) server
  address: 127.0.0.1
  # The port of the remote (Java Edition) server
  port: 25565
  # Authentication type. Can be offline, online, or floodgate (see https://github.com/GeyserMC/Geyser/wiki/Floodgate).
  auth-type: online
```
