### ISSUE TITLE
Scoreboard Doesn't Update

### ISSUE THREAD

**Issue by haloflooder** [GeyserMC/Geyser#1278]
**Describe the bug**

The scoreboard doesn't update when being displayed on a bedrock client. We have a world time on the scoreboard that refreshes every second. Works fine on java clients but it's just frozen on a bedrock clients.

**To Reproduce**

1. Install TAB Premium
2. Configurate the scoreboard
3. Join server
4. ???
5. ~~Profit~~ Frozen scoreboard

**Expected behavior**

We expect the scoreboard to update when the server sends a packet for the scoreboard.

**Screenshots / Videos**

Frozen on bedrock. Moving player around to show that scoreboard is static with both time and coords.
![frozen](https://i.imgur.com/Qeop674.gif)

Not frozen on java.
![frozen](https://i.imgur.com/Z0EzNj3.gif)

**Server Version**

Paper version git-Paper-134 (1.16.1)

**Geyser Version**

Geyser 1.1.0 (git-master-8c86308) as a bungeecord plugin (waterfall 1.16-R0.4)

**Minecraft: Bedrock Edition Version**

1.16.40

**Additional Context**

We're using the plugin TAB for scoreboards. Haven't used other plugins like kiteboard yet and our in-house scoreboard plugin produces different results compared to what I described above.

**Comment by DoctorMacc** [comment]
This is *likely* related to #1216.

**Comment by haloflooder** [comment]
@DoctorMacc I noticed that issue but thought it might've not been a formatting issue since the format on the scoreboard is correct.

**Comment by DoctorMacc** [comment]
Is there an example configuration of this we can use with a free version of TAB?

**Comment by haloflooder** [comment]
Unfortunately, the scoreboard function from TAB is only available in the premium version. However, you are completely free to compile the premium version from their github repo [here](https://github.com/NEZNAMY/TAB/#premium-code)

If you do decide to go through the effort to compile the plugin, here is a configuration file for "premiumconfig.yml"

<details><summary>Click to see config</summary>
  
```yaml
sorting-type: GROUPS
sorting-placeholder: '%some_level_maybe?%'
case-sentitive-sorting: true
unlimited-nametag-mode-dynamic-lines:
- abovename
- nametag
- belowname
- another
unlimited-nametag-mode-static-lines:
  myCustomLine: 0.66
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  use-numbers: true
  disable-in-worlds:
  - disabledworld
  default-scoreboard: serverstats
  per-world:
    testworld: default
  permission-required-to-toggle: false
  static-number: 0
scoreboards:
  serverstats:
    display-condition: permission:scoreboard.serverstats
    if-condition-not-met: default
    title: 'ServerNameHere'
    lines:
    - '&6  World Stats'
    - '&f    Players'
    - '&a    %online%/%server_max_players%'
    - '&f    World Time'
    - '&a    %player_world_time_12%'
    - '&f    TPS'
    - '&a    %spark_tps_5s%'
    - '&a    %spark_tps_10s%'
    - '&a    %spark_tps_1m%'
  default:
    title: 'ServerNameHere'
    lines:
    - '&6  World Stats'
    - '&f    Players'
    - '&a    %online%/%server_max_players%'
    - '&f    World Time'
    - '&a    %player_world_time_12%'
    - '&6  Your Coords'
    - '&a    %xPos%x %yPos%y %zPos%z'
scoreboard-on: '&2Scorebord enabled'
scoreboard-off: '&7Scoreboard disabled'
placeholder-output-replacements:
  '%essentials_vanished%':
    'Yes': '&7| Vanished'
    'No': ''
  '%tps%':
    '20': '&aPerfect'
allign-tabsuffix-on-the-right: false
extra-character-widths:
  65330: 6
  65365: 5

```
  
</details>

Something I did notice is that another old scoreboard plugin that I tested had similar formatting problems as that other issue. The difference between TAB and our old plugin is that TAB uses 100% packets while our old plugin utilizes scoreboard objects from spigot.
