### ISSUE TITLE
My server has multiple IP addresses, but geyser can only use one of them

### ISSUE THREAD

**Issue by 10935336** [GeyserMC/Geyser#1287]
**Describe the bug**
My server has multiple IP addresses for load balancing. These addresses are bound to different domain names. For some reasons, I did not use HAproxy.
After using Geyser, I added all the domain names in Bedrock Edition, but only one domain name can enter the server, and it is completely random. Every time I restart the bungeecord, a different domain name can enter.
In addition, my server has an IPv6 address, which is also unavailable
Although this is not a big problem, I still hope to be able to use all the lines.

config.yml:
```
bedrock:
  # The IP address that will listen for connections.
  # There is no reason to change this unless you want to limit what IPs can connect to your server.
  address: 0.0.0.0
  # The port that will listen for connections
  port: 19132
```

**To Reproduce**
1. Install geyser in bungeecord
2. Configuration
3. Add all server domain names to Bedrock Edition
4. See that only one domain name can connect to the server

**Expected behavior**
Should be able to connect to the server using all domains/IP addresses

**Server Version**
I use bungeecord version of geyser.
I use the waterfall fork Traverine.
Traverine version:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:ed11f57:160 by md_5 # 160
Server version: git-Paper-"d35903e" # 195

**Geyser Version**
Geyser version: git-master-8c86308
Not using Floodgate

**Minecraft: Bedrock Edition Version**
Android: v1.16.40
Windows10: beta 1.16.100.55
