### ISSUE TITLE
Right-click event not working with some items for other plugins (It used to work)

### ISSUE THREAD

**Issue by StarkyOficial** [GeyserMC/Geyser#2346]
### Describe the bug

We are using spawn eggs, buckets, etc with special events on right-clicks (on air), and since 1.17 has come out, those right-clicks stopped working for bedrock players (unless they use the spawn eggs, buckets, etc on the floor).

We use ItemsAdder plugin for the items events.

### To Reproduce

1. Configure a spawn egg, bucket or similar with an event on right-click.
2. Check if the event does work from a Bedrock Player.

(Example for ItemsAdder)
```
example:
    display_name: "&b&lexample"
    resource:
      material: BUCKET
      generate: false
      model_path: "item/example"
    events:
      interact:
        right:
          shoot_particle_first:
              name: FIREWORKS_SPARK
              distance: 30
          shoot_particle_second:
              name: CLOUD
              distance: 30
```

### Expected behaviour

Right-click event working on air.

### Server Version and Plugins

git-Paper-68 (MC: 1.17)

ProtocolLib
LoneLibs
ItemsAdder
Geyser-Spigot
floodgate

### Geyser Dump

https://dump.geysermc.org/Zos18lSy838CgXAWHViCEGMdeqYtuTZi

### Geyser Version

1.4.0-SNAPSHOT (git-master-7ae27c7)

### Minecraft: Bedrock Edition Version

1.17.2
