### ISSUE TITLE
`CustomModelData` mapping

### ISSUE THREAD

**Issue by AlexXanderGrib** [GeyserMC/Geyser#2542]
### What feature do you want to see added?

I think its possible to map java CustomModelData to bedrock custom items to hook up in resource packs. It could be done in config like this:

```yaml
custom-models-mapping:
  - myresource:gun:
      id: minecraft:crossbow
      CustomModelData: 15
```

### Are there any alternatives?

No
