### ISSUE TITLE
Bedrock players seeing java username as hearts (❤) and they dont exist on Java

### ISSUE THREAD

**Issue by MrRazamataz** [GeyserMC/Geyser#2563]
### Describe the bug

Im not sure whats causing it, my plugins that would even touch usernames like TAB, dont add hearts to players, and mcMMO only uses hearts for mobs. not players. Some Java players usernames show as a row of hearts, rather then the username.

### To Reproduce

Not sure how it happens, it just does?

### Expected behaviour

To show like this:
![image](https://user-images.githubusercontent.com/56600481/135762579-d7b1dddc-b5f1-456f-9517-f752ac4e26cf.png)

### Screenshots / Videos

Instead it shows like this, on bedrock only:
![image](https://user-images.githubusercontent.com/56600481/135762602-94f9afa9-4c6d-46d1-9b1d-ebb6b3abb7a4.png)

### Server Version and Plugins

`This server is running AirplanePurpur version git-AirplanePurpur-31 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)`

Plugins:
```
Plugins (87): AdvancedPortals, AnarchyExploitFixes*, AngelChest, AntiVPN, AuctionHouse, AutoAnnouncer*, BambooCollisionFix, BedrockPlayerManager, BetterSleeping4, Boss, BungeeChannel*, BungeeGuard, Citizens, CMILib, CombatLogX, CommandToItem, CoreProtect, CraftingStore, DeathMessages, DiscordSRV, DiscordSRV-Staff-Chat, DungeonsXL, Econoblocks, Essentials, EssentialsDiscord, EssentialsSpawn, floodgate, HolographicDisplays, InventoryRollbackPlus, ItemsXL, JukeBox, KCPluginPlugin, LibsDisguises, LimitCreative, LiteBans, LitePlaytimeRewards, LuckPerms, mcMMO, MMOItems, MobBanners, MultiWorld*, MyCommand, MythicLib, MythicMobs, NoCheatPlus, NoteBlockAPI, Oh_the_dungeons_youll_go, OpenInv, PandeLoot, PistonChat, PistonFilter*, PlaceholderAPI, Plan, PlayerWarps, PlugMan, ProtocolLib, PsudoCommand, QuickShop, Residence, RestartPlugin*, SaveRegion, Scoreboard-revision*, Sentinel, ServersNPC, SimplePets, SirBlobmanCore (SirBlobmanAPI, XSeries), SkinsRestorer, spark, SuperbVote, TAB, TabuuCore, Themis, TitleWelcomeMessage, Tweakin, VanishNoPacket, Vault, ViaBackwards, ViaVersion, Votifier, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, Worldstats*, XPBankZ, YamipaPlugin
```

### Geyser Dump

https://dump.geysermc.org/SwnhapDlx1IXCVOek5xJFLZDK0OdF56v

### Geyser Version

This server is running Geyser version 1.4.3-SNAPSHOT (git-master-6f4d433) (Java: 1.17.1, Bedrock: 1.17.10/1.17.11 - 1.17.30)

### Minecraft: Bedrock Edition Version

1.17.30 and older

**Comment by LegacyGamerHD** [comment]
likely has to todo with featherboard

**Comment by MrRazamataz** [comment]
> likely has to todo with featherboard

Dont have featherboard?

**Comment by Chew** [comment]
The hearts are definitely a mcMMO thing. 

It has a config to disable it:

```yml
Mob_Healthbar:
    # Enabled: Whether or not the feature is enabled at all
    # Display_Type: Per player Default display for mob health bars - HEARTS, BAR, or DISABLED
    # Display_Time: Amount of time (in seconds) to display. To display permanently, set to -1
    Enabled: true
    Display_Type: HEARTS
    Display_Time: 3
```
https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/config.yml#L149-L155

And I'm 99% sure there's a command for it as well, but I can't find it.

This is more of a workaround for the issue at large, though.
