### ISSUE TITLE
Custom Crafting no longer works for bedrock.

### ISSUE THREAD

**Issue by SamGamerYT** [GeyserMC/Geyser#3332]
### Describe the bug

A while ago players were able to craft through plugins like mmoitems, customcrafting now it doesn't work

### To Reproduce

https://gyazo.com/e4c05849d9f75a7d91070429dc1d82ec

### Expected behaviour

It should allow us to craft properly.

### Screenshots / Videos

https://gyazo.com/e4c05849d9f75a7d91070429dc1d82ec

### Server Version and Plugins

[06:58:28 INFO]: Current: git-Purpur-1809 (MC: 1.19.2)*
Previous: git-Purpur-1789 (MC: 1.19.2)
* You are running the latest version

### Geyser Version

Build #1206

### Additional Context

>....[06:58:39 INFO]: Collecting dump info
[06:58:39 ERROR]: Exception in thread "main" java.lang.NoClassDefFoundError: org/geysermc/geyser/dump/DumpInfo
[06:58:39 ERROR]:       at org.geysermc.geyser.command.defaults.DumpCommand.execute(DumpCommand.java:93)
[06:58:39 ERROR]:       at org.geysermc.geyser.platform.bungeecord.command.GeyserBungeeCommandExecutor.execute(GeyserBungeeCommandExecutor.java:71)
[06:58:39 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:212)
[06:58:39 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:163)
[06:58:39 ERROR]:       at io.github.waterfallmc.waterfall.console.WaterfallConsole.runCommand(WaterfallConsole.java:30)
[06:58:39 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87)
[06:58:39 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:168)
[06:58:39 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141)
[06:58:39 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:72)
[06:58:39 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[06:58:39 ERROR]: Caused by: java.lang.ClassNotFoundException: org.geysermc.geyser.dump.DumpInfo
[06:58:39 ERROR]:       at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
[06:58:39 ERROR]:       at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
[06:58:39 ERROR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[06:58:39 ERROR]:       ... 10 more

Dump didn't work

**Comment by onebeastchris** [comment]
Is this still an issue with the latest geyser version?

**Comment by SamGamerYT** [comment]
> 

Yuuuuuuuuuuuup

**Comment by SamGamerYT** [comment]
> okay, please attach a new dump file here. Newest version should have fixed dumps

Dump has been fixed already but it was more about the crafting system still not working

**Comment by SamGamerYT** [comment]
https://dump.geysermc.org/yHFF8iFksjYQMwpGACG6Dn1TFCZ9nFgl

**Comment by Hahaa13** [comment]
+1

**Comment by onebeastchris** [comment]
Does the issue still occur on the latest version? We recently overhauled Geyser internally with the protocol 3.0 update.

**Comment by SamGamerYT** [comment]
> Does the issue still occur on the latest version? We recently overhauled Geyser internally with the protocol 3.0 update.

Yes, Sadly it still does

**Comment by onebeastchris** [comment]
Thanks for the quick response - could you share a Geyser dump too?

**Comment by SamGamerYT** [comment]
https://dump.geysermc.org/Zw56XywLvLV4C5lIdVUkckMA05JbnYdx

**Comment by SamGamerYT** [comment]
https://gyazo.com/e230402a355421407df5a0c8b19a9a1c - Still doesn't work

**Comment by SamGamerYT** [comment]
I submitted this issue on Oct 2022 and now it's August 2023, the birthday is approaching.

**Comment by onebeastchris** [comment]
Could you send an example config for (what i assuming is customcrafting) that would help us reproduce the issue?
A video is great, reproduction steps even better.

**Comment by SamGamerYT** [comment]
Hi! It is not customcrafting, instead it's mmoitems and their standard recipe system

**Comment by SamGamerYT** [comment]
```
COPPER_MEDAL:
  base:
    material: SUNFLOWER
    name: '&6&lCOPPER &f&lMEDAL'
    tier: UNCOMMON
    enchants:
      unbreaking: 1
    hide-enchants: true
    disable-smelting: true
    disable-repairing: true
    crafting:
      shapeless:
        '1':
          input:
          - m MATERIAL A_ROCK_1 2.0..
          - v AIR - 1.0..
          - v AIR - 1.0..
          - v AIR - 1.0..
          - v AIR - 1.0..
          - v AIR - 1.0..
          - v AIR - 1.0..
          - v AIR - 1.0..
          - v AIR - 1.0..
          hidden: false
      smithing: {}
    disable-smithing: true
    disable-enchanting: true
    revision-id: 2
    ```
