### ISSUE TITLE
Lag for bedrock players (mostly mobile users)

### ISSUE THREAD

**Issue by MarkHarrisMedia** [GeyserMC/Geyser#5038]
### Describe the bug

Hello, I have a very established cross play server called Alpha MC.

I've noticed its always bedrock players that might happen to complain about lag, if any.

I've turned out view and simulation distance way down for now until something else fixes the problem. 

I noticed player heads create alot of lag for bedrock so i've told our players to remove them from their houses in excess.

We are running 1.21 Fabric JAVA server with the newest version of geyser and floodgate.

### To Reproduce

Play ALPHA Minecraft on Bedrock or Java:

Bedrock login
IP: 172.240.47.153
Port: 25543

Java Login
172.240.47.153:25584

### Expected behaviour

need to fix the lag for bedrock players, java players have not experienced lag at all

### Geyser Version

2.4.2-b673

### Minecraft: Bedrock Edition Device/Version

All Bedrock Players Experience Lag

### Additional Context

Only Bedrock Players Experiencing Lag. JAVA players report that it is working perfect.

**Comment by MarkHarrisMedia** [comment]
For more info from the players of our community, visit https://www.facebook.com/groups/alphaminecraft

**Comment by ChrisTVH** [comment]
In my network also my bedrock users report the same thing, even though I have all my instances together in a dedicated and a good location.

**Comment by Camotoy** [comment]
> I noticed player heads create alot of lag for bedrock so i've told our players to remove them from their houses in excess.

There are config options for these:
```yaml
# The maximum number of custom skulls to be displayed per player. Increasing this may decrease performance on weaker devices.
# Setting this to -1 will cause all custom skulls to be displayed regardless of distance or number.
max-visible-custom-skulls: 128

# The radius in blocks around the player in which custom skulls are displayed.
custom-skull-render-distance: 32
```
