### ISSUE TITLE
Black Particles on Mobs

### ISSUE THREAD

**Issue by SamGamerYT** [GeyserMC/Geyser#5183]
### Describe the bug

ModelEngine Mobs shows "Black Particles" around model mobs. 

### To Reproduce

```
test_npc:
  Type: ZOMBIE
  Display: '&r'
  Health: 100
  Damage: 0
  AIGoalSelectors:
  - clear
  AITargetSelectors:
  - clear
  Skills:
  - model{mid=discord2;d=false} @self ~onSpawn
  - model{mid=discord2;d=false} @self ~onLoad
  ```
  Particles show up

### Expected behaviour

```
test_npc:
  Type: ZOMBIE
  Display: '&r'
  Health: 100
  Damage: 0
  AIGoalSelectors:
  - clear
  AITargetSelectors:
  - clear
  ```
  Particles do not show up

### Screenshots / Videos

https://i.masel.io/ZIXO8/kAKaruMO82.jpg

### Geyser Dump

https://dump.geysermc.org/u6UlOdb8JPHmI3bI0CeXNm8d1vJhBJdb

### Geyser Version

2.5.1-b724 (git-master-9e276c1)

### Minecraft: Bedrock Edition Device/Version

Windows 10, Xbox, PS, Mobile
