### ISSUE TITLE
Invalid Header behind traefik reverse proxy

### ISSUE THREAD

**Issue by L-Wehmschulte** [GeyserMC/Geyser#5520]
### Describe the bug

I'm running a containerized version of the Geyser Standalone application behind a Traefik reverse proxy. I've set enable-proxy-protocol to true, but I'm getting the following Error, when enabling debug mode in the config:

**/172.24.0.4:44558 sent malformed PROXY header
io.netty.handler.codec.haproxy.HAProxyProtocolException: header length (over 1172) exceeds the allowed maximum (108)**

### To Reproduce

Setup a UDP entrypoint in Traefik:
```yml
mc-bedrock-udp:
    address: ':19132/udp'
```

Setup geyser container:
```yml
services:
  bedrock-router:
    image: dev.lwehmschulte.de/geysermc-docker/geysermc-docker:0.0.4
    container_name: bedrock-router
    extends:
      file: /docker/common/compose_base.yml
      service: app
    networks:
      - internal
    volumes:
      - ./config/geyser/config.yml:/app/config.yml:ro
      - ./config/geyser/saved-auth-chains.json:/app/saved-auth-chains.json
    labels:
      - traefik.udp.routers.bedrock-router-udp.entrypoints=mc-bedrock-udp
      - traefik.udp.routers.bedrock-router-udp.service=bedrock-router-udp
      - traefik.udp.services.bedrock-router-udp.loadbalancer.server.port=19132

      - traefik.enable=true
      - traefik.docker.network=internal
networks:
  internal:
    external: true
```

### Expected behaviour

Geyser should accept the connection from Traefik and use the URL from the Proxy header

### Screenshots / Videos

Traefik logs:

![Image](https://github.com/user-attachments/assets/927e05fe-e7c2-43b3-b778-147100122dc5)

Full Stacktrace:
[15:27:41 DEBUG] /172.24.0.4:44558 sent malformed PROXY header
bedrock-router  | io.netty.handler.codec.haproxy.HAProxyProtocolException: header length (over 1172) exceeds the allowed maximum (108)
bedrock-router  |       at org.geysermc.geyser.network.netty.proxy.ProxyProtocolDecoder.fail(ProxyProtocolDecoder.java:419) ~[geysermc.jar:?]
bedrock-router  |       at org.geysermc.geyser.network.netty.proxy.ProxyProtocolDecoder.failOverLimit(ProxyProtocolDecoder.java:410) ~[geysermc.jar:?]
bedrock-router  |       at org.geysermc.geyser.network.netty.proxy.ProxyProtocolDecoder$HeaderExtractor.extract(ProxyProtocolDecoder.java:502) ~[geysermc.jar:?]
bedrock-router  |       at org.geysermc.geyser.network.netty.proxy.ProxyProtocolDecoder.decodeLine(ProxyProtocolDecoder.java:405) ~[geysermc.jar:?]
bedrock-router  |       at org.geysermc.geyser.network.netty.proxy.ProxyProtocolDecoder.decodeHeader(ProxyProtocolDecoder.java:100) ~[geysermc.jar:?]
bedrock-router  |       at org.geysermc.geyser.network.netty.proxy.ProxyProtocolDecoder.decode(ProxyProtocolDecoder.java:96) ~[geysermc.jar:?]
bedrock-router  |       at org.geysermc.geyser.network.netty.proxy.ProxyServerHandler.channelRead0(ProxyServerHandler.java:64) [geysermc.jar:?]
bedrock-router  |       at org.geysermc.geyser.network.netty.proxy.ProxyServerHandler.channelRead0(ProxyServerHandler.java:43) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [geysermc.jar:?]
bedrock-router  |       at org.cloudburstmc.netty.handler.codec.raknet.ProxyInboundRouter.channelRead(ProxyInboundRouter.java:66) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.epoll.EpollDatagramChannel.processPacket(EpollDatagramChannel.java:662) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.epoll.EpollDatagramChannel.recvmsg(EpollDatagramChannel.java:697) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.epoll.EpollDatagramChannel.access$300(EpollDatagramChannel.java:56) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:536) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) [geysermc.jar:?]
bedrock-router  |       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) [geysermc.jar:?]
bedrock-router  |       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [geysermc.jar:?]
bedrock-router  |       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [geysermc.jar:?]
bedrock-router  |       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [geysermc.jar:?]
bedrock-router  |       at java.lang.Thread.run(Thread.java:1447) [?:?]

### Geyser Version

2.7.0-b818 (git-master-b06f1ed)
