### ISSUE TITLE
Unable to connect to world

### ISSUE THREAD

**Issue by communityfablab** [GeyserMC/Geyser#66]
Hi all - thank you so much for making this project and developing this code. We've recently been awarded an NSF grant to help kids learn about exoplanets though Minecraft simulations and our current server, based on Java/Bukkit, will need to be able to host hoards of helpless children with access to only Minecraft PE. I've been working on setting up a Geyser this weekend with no luck. Here's what all I've tried:

-Geyser build 108 from Oct 18; prior to this Dragon Proxy (0.0.2-snapshot and 3.4.6)
-Our regular Bukkit server 1.14.4, a temporary blank/default Forge server on 1.12.2 and a temporary default vanilla Minecraft server on 1.14.4
-Minecraft PE on Android and iOS 1.12.1
-No ports are on our server are nonstandard, no firewalls, regular connections all work fine
-Confirmed connecting PE devices to another Geyser-forwarded server and it worked okay

I'm using the following settings in the configuration file:

```
bedrock:
  # The IP address that will listen for connections
  address: 0.0.0.0
  # The port that will listen for connections
  port: 19132
  # The MOTD that will be broadcasted to Minecraft: Bedrock Edition clients
  motd1: "Fab Lab Test"
remote:
  # The IP address of the remote (Java Edition) server
  address: 192.17.189.137
  # The port of the remote (Java Edition) server
  port: 25565

  # Authentication type. Can be offline, online, or hybrid (see the wiki).
  auth-type: online
```
Neither Minecraft PE install can see any info about the server and gives the "Unable to connect to world" response when we attempt to force it. I've attached my config file here, I'm not sure what else to do. Any suggestions?

I realize you probably get silly newbies like my self asking for help often, I'd be happy to help make a guide or tutorial to help folks get past the issue I'm having if we're able to figure out what it is!
