### ISSUE TITLE
Docker & Remote IP

### ISSUE THREAD

**Issue by toguno** [GeyserMC/Geyser#887]
We are using the bungee plugin and everything was working for a few hours. Then, likely due to pebblehost, our remote ip changed. Upon bungee reboot we got this message:

`01.07 15:54:18 [Server] WARN [Geyser-BungeeCord]: You are most likely in a Docker container, this may cause connection issues from Geyser to the Java server`
`01.07 15:54:18 [Server] WARN [Geyser-BungeeCord]: We recommended using the following IP as the remote address: 172.17.0.3`

As geyser already detects the new ip to aim at, could there be a setting allowing geyser to automatically aim at this ip? Otherwise, geyser would be untenable on our setup as the remote ip address of the java server keeps on changing (something to do with docker), and would require constant updating in the config.

**Comment by Resi23** [comment]
have you try use Containernames?
```
remote:
  # The IP address of the remote (Java Edition) server
  address: citybuild1
  # The port of the remote (Java Edition) server
  port: 25565
  # Authentication type. Can be offline, online, or floodgate (see https://github.com/GeyserMC/Geyser/wiki/Floodgate).
  auth-type: online
```

I use Containernames in my Waterfall Config
```
servers:
  CB:
    motd: |-
      &6&lCB &e~ &cDein 1.16.1 &e ~ CityBuild Server
    address: citybuild1:25565
```
